window.CONFIG = {
  macros: [
    { category: 'Entertainment', name: 'YouTube', triggers: ['y', 'yt', 'youtube'], key: 'KeyY', icon: 'youtube', url: 'https://youtube.com', normalisedURL: 'youtube.com', commands: { go: { template: 'https://youtu.be/{$}', description: 'gotovideo' }, search: { template: '{@}/results?search_query={$}' } }, bgColor: { type: 'solid', color: '#f30002' }, textColor: '#212121', pinned: true },
    { category: 'Programming', name: 'GitHub', icon: 'github', url: 'https://github.com', normalisedURL: 'github.com', triggers: ['g', 'git', 'github'], key: 'KeyG', commands: { go: { template: '{@}/{$}', description: 'gotouser' }, search: { template: '{@}/search?q={$}' } }, bgColor: { type: 'solid', color: '#171515' }, textColor: '#e8e8e8', pinned: true },
    { category: 'Programming', name: 'StackOverflow', icon: 'stackoverflow', url: 'https://stackoverflow.com', normalisedURL: 'stackoverflow.com', triggers: ['s', 'st', 'so', 'stack', 'stackoverflow'], key: 'KeyS', commands: { search: { template: '{@}/search?q={$}' }, go: { template: '{@}/questions/{$}', description: 'gotoquestion' } }, bgColor: { type: 'gradient', gradientType: 'linear', colors: ['#e87922', '#ffbe25'], stops: [0, 100] }, textColor: '#212121', pinned: true },
    { category: 'Other', name: 'Translate', icon: 'translate', url: 'https://translate.google.com', normalisedURL: 'translate.google.com', triggers: ['t', 'translate'], key: 'KeyT', commands: { search: { template: '{@}/?text={$}', description: 'translatetext' } }, bgColor: { type: 'gradient', gradientType: 'linear', angle: 45, colors: ['#508bed', '#4654b4'] }, textColor: '#fff', pinned: true },
    { category: 'Music', name: 'spotify', icon: 'spotify', url: 'https://open.spotify.com', normalisedURL: 'spotify.com', triggers: ['music', 'sp', 'sfy', 'spo', 'spotify'], commands: { search: { template: '{@}/search/{$}' }, go: { template: '{@}/track/{$}', description: 'gototrack' } }, bgColor: { type: 'solid', color: '#1ccc5b' }, textColor: '#000', pinned: true },
    { category: 'Communication', name: 'Outlook', icon: 'outlook', url: 'https://outlook.office365.com/', normalisedURL: 'outlook.office365.com/', triggers: ['o', 'ol', 'mail', 'm'], key: 'KeyM', bgColor: { type: 'gradient', gradientType: 'linear', angle: 45, colors: ['#df493b', '#df493b'], stops: [50, 100] }, textColor: '#e8e8e8', pinned: true },
    { category: 'Work', name: 'GoogleDrive', triggers: ['gd', 'drive', 'gdrive', 'google'], icon: 'gdrive', url: 'https://drive.google.com', normalisedURL: 'drive.google.com', bgColor: { type: 'gradient', angle: 70, gradientType: 'linear', colors: ['#2684fc', '#00ac47', '#ffba00'] }, textColor: '#fff', pinned: true },
    { category: 'Shopping', name: 'Amazon', triggers: ['a', 'am', 'amz', 'amazon'], icon: 'amazon', key: 'KeyA', url: 'https://www.amazon.com/', normalisedURL: 'amazon.com', bgColor: { type: 'gradient', gradientType: 'linear', colors: ['#f29100', '#fff'], stops: [0, 80] }, textColor: '#000', pinned: true },
    { category: 'Education', name: 'Wikipedia', icon: 'wikipedia', triggers: ['w', 'wiki', 'wikipedia'], url: 'https://www.wikipedia.org', normalisedURL: 'wikipedia.org', commands: { search: { template: '{@}/?search={$}' }, go: { template: '{@}/wiki/{$}' } }, bgColor: { type: 'gradient', gradientType: 'linear', colors: ['#e1e1e3', '#bbb'], stops: [60, 100] }, textColor: '#000', pinned: true },
    { category: 'Calendar', name: 'SOCS', triggers: ['socs', 'c', 'calendar', 'cms', 'sock'], url: 'https://www.socscms.com/login/161?', normalisedURL: 'www.socscms.com/login/161?', bgColor: { type: 'solid', color: '#e37151' }, textColor: '#e8e8e8' },
    { category: 'Search', name: 'Bing', triggers: ['b', 'bing'], url: 'https://www.bing.com', normalisedURL: 'bing.com', commands: { search: { template: '{@}/search?q={$}' } }, bgColor: { type: 'gradient', gradientType: 'linear', colors: ['#3ab0f1', '#2351dd', '#40d1da'] }, textColor: '#e8e8e8' },
    { category: 'Search', name: 'Yandex', triggers: ['ya', 'yandex'], url: 'https://ya.ru', normalisedURL: 'ya.ru', commands: { search: { template: '{@}/search/?text={$}' } }, bgColor: { type: 'solid', color: '#fc3f1d' }, textColor: '#000' }
  ],
  commands: [
    { type: 'search', trigger: '?' },
    { type: 'go', trigger: '/' }
  ],
  engines: {
    google: { name: 'Google', bgColor: { type: 'solid', color: '#aaa' }, textColor: '#fff', types: { query: { template: 'https://www.google.com/search?q={$}' }, calculator: { template: 'https://www.google.com/search?q={@}' }, currency: { template: 'https://www.google.com/search?q={@}' } } },
    duckDuckGo: { name: 'DuckDuckGo', bgColor: { type: 'solid', color: '#e37151' }, textColor: '#e8e8e8', types: { query: { template: 'https://duckduckgo.com/?q={$}' }, calculator: { template: 'https://duckduckgo.com/?q={@}' }, currency: { template: 'https://duckduckgo.com/?q={@}' } } },
    bing: { name: 'Bing', bgColor: { type: 'gradient', gradientType: 'linear', colors: ['#3ab0f1', '#2351dd', '#40d1da'] }, textColor: '#e8e8e8', types: { query: { template: 'https://www.bing.com/search?q={$}' }, calculator: { template: 'https://www.bing.com/search?q={@}' }, currency: { template: 'https://www.bing.com/search?q={@}' } } },
    brave: { name: 'Brave', bgColor: { type: 'gradient', gradientType: 'linear', colors: ['#FB542B', '#343546'] }, textColor: '#e8e8e8', types: { query: { template: 'https://search.brave.com/search?q={$}' }, calculator: { template: 'https://search.brave.com/search?q={@}' }, currency: { template: 'https://search.brave.com/search?q={@}' } } }
  }
};
